version: '1.0'
name: pipeline-android-book
displayName: pipeline-android-book
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
    commitMessages:
      include:
        - .*build.*
stages:
  - name: stage-android-book
    displayName: stage-android-book
    strategy: naturally
    trigger: auto
    executor:
      - zhongziming
    steps:
      - step: build@python
        name: build_python
        displayName: build_python
        pythonVersion: '3.9'
        artifacts:
          - name: outputs
            path:
              - ../
        commands:
          - ' python3 -m pip install --upgrade pip'
          - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - pip3 install -r requirements.txt
          - python3 ./main.py ../outputs $ZZM_FTP
  - name: upload-android-book
    displayName: upload-android-book
    strategy: naturally
    trigger: auto
    executor:
      - zhongziming
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: publish_general_artifacts
        dependArtifact: outputs
        artifactRepository: default
        artifactName: output
permissions:
  - role: admin
    members:
      - zhongziming
